# Generated by Django 5.0.1 on 2024-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(max_length=32),
        ),
    ]
